version: '3.8'
services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql

  mysql:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dependencias_db
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Admin@2025
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dependencias_db.sql:/docker-entrypoint-initdb.d/dependencias_db.sql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root

volumes:
  mysql-data: